### ISSUE TITLE
D3v5 compatibility 

### ISSUE THREAD

**Issue by chakraborty-slx** [patorjk/d3-context-menu#53]
I am trying to use d3v5 dagre-d3 and d3-context-menu .
   

    "d3": "^5.16.0",
    "d3-context-menu": "^1.1.2",
    "dagre-d3": "^0.6.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"

d3-context-menu.dew.js:122 Uncaught TypeError: d3.selectAll is not a function
    at SVGGElement.<anonymous> (VM990 d3-context-menu.dew.js:122)
    at SVGGElement.<anonymous> (VM1310 d3-selection.dew.js:722)
(anonymous) @ d3-context-menu.dew.js:122
(anonymous) @ d3-selection.dew.js:722

Here is the plunker to reproduce the problem.

https://plnkr.co/edit/t4CKN9IaBvO35uKd

Please let me know if you require other info.

**Comment by patorjk** [comment]
I haven't used D3 version 5 yet. Poking around a bit, it looks like the library would need to be changed to export the anonymous function in https://github.com/patorjk/d3-context-menu/blob/master/js/d3-context-menu.js rather auto-executing it with the *this* object (which for most cases was the window object). Then when imported the function would simply need to be invoked with the d3 object.

If you're interested in doing this I'd accept a PR. If not I can tackle this, but I'm not sure on the time frame.

**Comment by chakraborty-slx** [comment]
I will give it a try and create PR .

**Comment by ngg** [comment]
I can use the latest version (1.1.2) with no issues with D3 5.16.0.
However D3 6.0 is out now, which has breaking changes in the event handling logics, and this plugin no longer works. I'll open a separate issue for that.

**Comment by patorjk** [comment]
Fixed in latest release.

**Comment by its-a-feature** [comment]
I know this is marked as closed, but I'm still getting this error, even with the latest:
```
"d3": "^5.16.0",
"d3-context-menu": "^2.1.0",
"dagre-d3": "^0.6.4",
```
I can run 
```
import * as d3 from 'd3';
import contextMenu from 'd3-context-menu';
...
.on("contextmenu", contextMenu(node_events["contextmenu"]));
```
And i get the same issue as described above - instead of getting a popup menu where i right-click, i get a text of my data in the bottom-left corner

**Comment by Rudgey84** [comment]
TypeError: Cannot read property 'pageX' of null is still an issue 
```
"d3": "^5.16.0",
"d3-context-menu": "^2.1.0",
```
